### PR TITLE
Update Semaphore.php

### PR DESCRIPTION
**Pull request by vologab**
It's needed when we do (for semaphores limiting):
$a=$p->getSharedMemory();
$a->remove(); 
inside our code

### CODE REVIEW

**Comment by misterion** [comment]
It does not make sense - at line 88 we always would have $this->isAcquired = false and remove() would not be called.

**Comment by vologab** [comment]
It's make sense.... At line 88 we have consecutive conditions,but not nested (first -false, second - true)... So when tasks completed and inside task we was removed semaphores... When desctructor called nothing to remove and it's reason for PHP Warnings

**Comment by misterion** [comment]
Let's expand desctructor code

```php
if ($this->isAcquired) {
    $this->isAcquired = !sem_release($this->mutex); //$this->release()
}

if ($this->pid === getmypid() && $this->isAcquired) {
    $this->remove();
}
```

Did you mean that you condition make sense if `sem_release` return `false`? Sorry for that, but i realy do not understand.

p.s. Please keep in mind that your never need to destroy semaphore and shared memory from child process. Look at [this topic](http://stackoverflow.com/questions/23487723/right-strategy-with-shared-memory-and-semaphore-removing-in-raii-like-php-class) about it.

**Comment by vologab** [comment]
I have such piece  of code:

					`$manager = new Ko\ProcessManager();

					foreach ($selIDs as $markId => $markName)
					{
						//Фиксируем модели и поколения в данной в категории и для марки

						if ($SyncModels AND (($onlyModel == $markName) OR !$onlyModel))
						{

							$this->catObject->Logger('Синхронизируем марку (код:' . $markId . ') ' . $markName . ' в категории ' . $value['id'], 'INFO');

							//Запускаем эти операции параллельно
							$manager->fork(function (Ko\Process $p) use ($value, $markId, $markName)
							{
								$this->SyncModels($markId, $value['id'], $value['data']['name']);

								$this->catObject->Logger('Завершена синхронизация марки  (код:' . $markId . ') ' . $markName . ' в категории ' . $value['id'], 'INFO');
								$a=$p->getSharedMemory();
								$a->remove();
								$p->kill();

								return;
							});
							//Реализуем асинхронную многопоточность
							while (($manager->count()) >= ($this->maxParallelThreads))
							{
								$manager->dispatch();
								sleep(1);
							}
						}
					}

					$manager->wait();`

So, If I doesn't remove shared memory, I have semaphores limit overflow

**Comment by misterion** [comment]
You do not need to call remove() and kill() in child process. The process would die as is and semaphore would be destroed in parent process. Look at `ProcessManager::childProcessDie()` code. If child process die the Process object would be removed from internal children map and process desctructor would be called. The shared memory (and semaphore) should be deleted by garbadge collector in that situation. Is it so in your case?

**Comment by vologab** [comment]
No, In my case I have  growing up of semaphore count (I see it in console with   ipcs -s  ) and limit overflow( if not'remove manual shared memory - $a->remove())

**Comment by misterion** [comment]
Could you check this behaviour if add `gc_collect_cycles();` just after `unset($this->children[$pid]);` in `ProcessManager::childProcessDie()`?

**Comment by misterion** [comment]
Also, as hot-fix you may add `gc_collect_cycles();` right after `Реализуем асинхронную многопоточность` while. 
p.s. I'm still trying to understand why objects are not picked up by the garbage collector in the parent process.

**Comment by vologab** [comment]
``` gc_collect_cycles(); just after unset($this->children[$pid]); in ProcessManager::childProcessDie()?```

It's solution! All work fine after it

**Comment by misterion** [comment]
I commit it under tag  v0.5.2. And big thanks for your help!

**Pull request closed without merging**
